import { Area, AreaChart, Bar, BarChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts'
import { ArrowUpRight, CalendarCheck, CreditCard, Megaphone, Plus, UsersRound } from 'lucide-react'
import { PageHeader } from '../components/layout/AppShell'
import { Button } from '../components/ui/Button'
import { Card, CardHeader, CardTitle } from '../components/ui/Card'
import { Skeleton } from '../components/ui/Skeleton'
import { attendanceData, feeData, notices, stats } from '../data/mockData'

export default function AdminDashboard() {
  return <><PageHeader eyebrow="Admin dashboard" title="Campus operations at a glance" description="Monitor attendance, revenue, notices, and key operational workflows from a polished executive cockpit." action={<Button><Plus size={18} /> Quick add</Button>} />
    <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{stats.map((s) => <Card key={s.label} className="overflow-hidden"><div className={`mb-5 h-2 w-20 rounded-full bg-gradient-to-r ${s.tone}`} /><p className="text-sm text-muted-foreground">{s.label}</p><div className="mt-2 flex items-end justify-between"><p className="text-3xl font-black">{s.value}</p><span className="rounded-full bg-emerald-50 px-3 py-1 text-xs font-bold text-emerald-600 dark:bg-emerald-500/10">{s.delta}</span></div></Card>)}</div>
    <div className="mt-6 grid gap-6 xl:grid-cols-3"><Card className="xl:col-span-2"><CardHeader><CardTitle>Attendance Analytics</CardTitle><Button variant="secondary" size="sm">Monthly</Button></CardHeader><div className="h-80"><ResponsiveContainer><AreaChart data={attendanceData}><defs><linearGradient id="attendance" x1="0" y1="0" x2="0" y2="1"><stop offset="5%" stopColor="#6366f1" stopOpacity={0.4}/><stop offset="95%" stopColor="#6366f1" stopOpacity={0}/></linearGradient></defs><CartesianGrid strokeDasharray="3 3" vertical={false}/><XAxis dataKey="month"/><YAxis/><Tooltip/><Area type="monotone" dataKey="present" stroke="#6366f1" fill="url(#attendance)" strokeWidth={3}/></AreaChart></ResponsiveContainer></div></Card>
      <Card><CardHeader><CardTitle>Fee Collection</CardTitle><CreditCard className="text-indigo-500" /></CardHeader><div className="h-80"><ResponsiveContainer><BarChart data={feeData}><CartesianGrid strokeDasharray="3 3" vertical={false}/><XAxis dataKey="month"/><YAxis/><Tooltip/><Bar dataKey="collected" fill="#6366f1" radius={[12,12,0,0]}/><Bar dataKey="pending" fill="#c7d2fe" radius={[12,12,0,0]}/></BarChart></ResponsiveContainer></div></Card></div>
    <div className="mt-6 grid gap-6 lg:grid-cols-3"><Card><CardHeader><CardTitle>Recent Notices</CardTitle><Megaphone className="text-indigo-500" /></CardHeader><div className="space-y-3">{notices.map((n) => <div key={n.title} className="rounded-2xl bg-muted p-4"><p className="font-bold">{n.title}</p><p className="text-xs text-muted-foreground">{n.date}</p></div>)}</div></Card><Card><CardHeader><CardTitle>Quick Actions</CardTitle><ArrowUpRight className="text-indigo-500" /></CardHeader><div className="grid gap-3">{[['Add Student', UsersRound], ['Mark Attendance', CalendarCheck], ['Create Notice', Megaphone]].map(([label, Icon]) => <Button key={label} variant="secondary" className="justify-start"><Icon size={18} />{label}</Button>)}</div></Card><Card><CardHeader><CardTitle>Loading State Preview</CardTitle></CardHeader><Skeleton className="h-24"/><Skeleton className="mt-3 h-12"/><Skeleton className="mt-3 h-12"/></Card></div></>
}
